




.build/leonardo/src/fast_line.cpp : src/fast_line.ino
	@mkdir -p .build/leonardo/src
	@echo [93msrc/fast_line.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/leonardo/src/fast_line.cpp
	@true

