




.build/leonardo/src/battle.cpp : src/battle.ino
	@mkdir -p .build/leonardo/src
	@echo [93msrc/battle.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/leonardo/src/battle.cpp
	@true

